name: paymentservice-ci
on:
  push:
    branches: [main]
    paths:
      - 'src/paymentservice/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/paymentservice/**'

  workflow_dispatch:




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
            context: ./src/paymentservice
            push: true
            tags: ghcr.io/${{ github.actor }}/microservices-devops-project-paymentservice:latest
